# https://mrsnailo.github.io
baseURL = "https://mrsnailo.github.io"
languageCode = 'en-us'
title = 'Shahid Parvez'
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = 'en'
enableEmoji = true
custom_css = ["/css/timeline.css"]

[languages.bn]
contentDir = "content/bn"
weight = 1
LanguageName = ':bangladesh:'

[languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[outputs]
    home = ["HTML", "RSS", "JSON" ] 


#set permalinks for posts 
[permalinks]
  posts = '/:year/:month/:day/:title/'

[module]
[[module.import]]
path = "github.com/adityatelange/hugo-PaperMod.git"
