[profileMode]
enabled = true
title = "শাহিদ পারভেজ"
subtitle = "Linux lover - Tech enthusiast - Student"
imageUrl = "/assets/logo/logo.png"
imageTitle = "Logo"
imageWidth = 180
imageHeight = 180


[[profileMode.buttons]]
name = "আমাকে জানুন"
url = "about"
# entry 2
[[profileMode.buttons]]
name = 'পোস্ট`স'
url = 'posts/'

[editPost]
    URL = "https://github.com/mrsnailo/mrsnailo.github.io/tree/master/content/bn"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link
