author = "Shahid Parvez"
defaultTheme = 'dark'

ShowShareButtons = true 
ShowReadingTime = true
showToc = true
tocOpen = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = true
images = ['/assets/cover/cover.png']

[label]
text = "‍@mrsnailo"
icon = "/assets/logo/logo.png"
iconHeight = 32


[assets]
disableFingerprinting = true
favicon = "/assets/icons/favicon/favicon-48x48.png"
favicon16x16 = "/assets/icons/favicon/favicon-16x16.png"
favicon32x32 = "/assets/icons/favicon/favicon-32x32.png"
apple_touch_icon = '/assets/icons/apple/base.png'
safari_pinned_tab = "/assets/icons/apple/tab.svg"
msTileColor = "#1d1e20"
vtag = '8jl4JnrGke'


[cover]
image = ['/assets/cover/cover.png']
alt = "Cover"
captions = "Reading Makes You Feel Good"


[[profileMode.buttons]]
name = "About Me"
url = "/en/about"
# entry 2
[[profileMode.buttons]]
name = 'Posts'
url = '/en/posts/'

# Social Icon

[[socialIcons]]
name = "Github"
url = "https://github.com/mrsnailo"

[[socialIcons]]
name = "Twitter"
url = "https://twitter.com/mrsnailo"

[[socialIcons]]
name = "Reddit"
url = "https://reddit.com/u/mrsnailo"

[[socialIcons]]
name = "Instagram"
url = "https://Instagram.com/mrsnailo"

[[socialIcons]]
name = "Telegram"
url = "https://t.me/mrsnailo"

[[socialIcons]]
name = "Discord"
url = "https://discord.com/users/573172734767661056"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]